### ISSUE TITLE
Remove redundant requirements from the controller

### ISSUE THREAD

**Issue by rakvium** [Danchek/RubyParsing#1]
Requirements of `rubygems` and `nokogiri` aren't needed, as far as you're using Gemfile.
https://github.com/Danchek/RubyParsing/blob/master/app/controllers/parsings_controller.rb#L1
https://github.com/Danchek/RubyParsing/blob/master/app/controllers/parsings_controller.rb#L2

**Comment by Danchek** [comment]
I've deleted them

**Comment by rakvium** [comment]
@Danchek, oh, cool! :laughing:
